### ISSUE TITLE
Deploy setuptools-pyecore to PyPI and GitHub releases

### ISSUE THREAD

**Issue by ferraith** [ferraith/setuptools-pyecore#21]
The deployment of setuptools-pyecore should be automated. The package should be deployed to the following web services:
* GitHub Releases
* PyPI

For GitHub Releases the organization account of pyecore should be used. Only a binary distribution (wheel package) should be deployed.

For PyPi the personal account of ferraith should be used. A source and a binary distribution of setuptools-pyecore should be deployed.

**Comment by ferraith** [comment]
@aranega : Can you provide me a personal access token for the deployment to GitHub releases please? (Org --> Settings --> Developer Settings --> Personal Access Token). I can't generate a new one because this is a organization setting. I attached an example. 
![personalaccesstoken](https://user-images.githubusercontent.com/2198040/44652896-7af4b180-a9ed-11e8-9741-8bf09925094b.jpg)

**Comment by aranega** [comment]
@ferraith Sure! However, I don't find the "Personnal access tokens" section in the "Developer Settings" of the organization (only OAuth and Github Apps). Is there another way of generating a new one? The only one I can generate are from my personnal account.
